spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/wimaster?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
        slave_1:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/wisalve?useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
   